### ISSUE TITLE
Vendors - create, delete, update

### ISSUE THREAD

**Issue by Gabrielle-Tobermann** [nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard#21]

**Comment by Greenfin17** [comment]
- [x] As a user, I should be able to add new vendors
- [x] As a user, I should be able to delete vendors
- [x] As a user, I should be able to edit the vendors

**Comment by Greenfin17** [comment]
Delete functionality was added while completing this bug fix.
https://github.com/nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard/pull/49
