### ISSUE TITLE
Equipment - create, delete, update

### ISSUE THREAD

**Issue by Gabrielle-Tobermann** [nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard#22]
Complete functionality to allow users to add new equipment, delete equipment and edit the equipment cards.
Buttons, event listeners, promises, functions and calls.

**Comment by Greenfin17** [comment]
- [ ] As a user, I should be able to add new equipment
- [ ] As a user, I should be able to delete equipment
- [ ] As a user, I should be able to edit the equipment
