### ISSUE TITLE
Workflow diagram

### ISSUE THREAD

**Issue by Gabrielle-Tobermann** [nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard#5]

**Comment by Greenfin17** [comment]
- [x] Create workflow diagram.

**Comment by Greenfin17** [comment]
https://lucid.app/lucidchart/48d101fb-5c19-41c9-86aa-5155fc78248b/edit?beaconFlowId=5EEF99802B7B5C5A&page=0_0#
